:modules:
  - hammer_cli_foreman
#  - hammer_cli_katello_bridge

:foreman:
    :host: 'https://localhost/'
    :username: 'admin'
    :password: 'changeme'

:log_dir: '~/.foreman/log'
:log_level: 'error'
